version: '3'

volumes:
  local_mongodb_data: {}

services:
  web: &cve_search
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: cve_search
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "5050:5000"
    command: /app/start-webserver.sh

  redis:
    image: redis:5.0.4
    ports:
        - "6379:6379"

  mongodb:
    image: mongo:4.0.4
    ports:
      - "27017:27017"      
    volumes:
      - local_mongodb_data:/data/db